trigger:
  branches:
    include: [main]
  tags:
    include: ['v*']
pr:
  branches:
    include: ['*']
pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
    fetchDepth: 0
  - script: |
      curl -fsSL https://app.gravitydocs.io/install.sh | GRAVITY_VERSION=1 GRAVITY_INSTALL_DIR="$HOME/.local/bin" sh
      "$HOME/.local/bin/gravity" run
    displayName: Gravity
    env:
      GRAVITY_REPO_TOKEN: $(GRAVITY_REPO_TOKEN)
      GRAVITY_TOKEN: $(GRAVITY_TOKEN)
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
