package cli

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/impulso/gravity-cli/internal/api"
	"github.com/impulso/gravity-cli/internal/git"
)

// selfdocSpaceDescription is the canonical description applied to the dedicated
// CLI-documentation space on every run.
const selfdocSpaceDescription = "Living reference for the Gravity CLI itself — command tree, flags, and exit codes, regenerated by `gravity selfdoc` on every run and verified against the CLI source."

// rootSourceRef is the repo-relative file every machine block binds to when a
// more specific per-command source file cannot be determined. The drift checker
// hashes this file, so it must exist in the CLI repo.
const rootSourceRef = "internal/cli/root.go"

// commandSourceRefs maps a command's name path (space-joined, e.g. "check api")
// to the repo-relative source FILE that defines it, so machine blocks can bind
// to the most specific real file. Anything not listed falls back to rootSourceRef.
var commandSourceRefs = map[string]string{
	"version":       "internal/cli/version.go",
	"init":          "internal/cli/init.go",
	"auth":          "internal/cli/auth.go",
	"doctor":        "internal/cli/doctor.go",
	"release-notes": "internal/cli/releasenotes.go",
	"check":         "internal/cli/check.go",
	"check api":     "internal/cli/check_api.go",
	"check docs":    "internal/cli/check_docs.go",
	"selfdoc":       "internal/cli/selfdoc.go",
}

func newSelfdocCmd(gf *globalFlags) *cobra.Command {
	var (
		space  string
		output string
		dryRun bool
		title  string
	)
	cmd := &cobra.Command{
		Use:   "selfdoc",
		Short: "Generate and propose documentation for the Gravity CLI itself",
		Long: `Walk the CLI's own command tree and emit a documentation space describing
every command, its flags, and the exit-code contract. The reference page is
generated deterministically from the cobra tree and the CLI source files — no
AI/agent loop is involved — and each machine block is bound to a real repo file
(sourceBinding kind "cli") so the drift checker can re-verify it later.

Pages produced (in the --space space, default "cli"):
  command-reference  machine blocks: command tree, flags, exit codes (drift-locked)
  overview           a single hybrid intro block a human may freely edit

Output modes:
  proposal  upsert both pages to Gravity as drafts + open proposals (default)
  stdout    print the generated blocks as text without posting`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			switch output {
			case outputProposal, outputStdout:
			default:
				return Failf(CodeError, "invalid --output %q (want proposal|stdout)", output)
			}

			e, err := resolveEnv(*gf, space)
			if err != nil {
				return err
			}
			// Resolve the target space with the documented precedence
			// (flag > env > config). The flag default is empty so GRAVITY_SPACE /
			// .gravity.yaml are honoured; the command's own default applies only
			// when nothing else is set.
			sp := e.cfg.Space
			if sp == "" {
				sp = "cli"
			}
			site, err := e.requireSite()
			if err != nil {
				return err
			}

			// The full command tree is rooted at the freshly-assembled root so the
			// reference reflects exactly what this binary exposes.
			root := NewRootCommand()

			refTitle := title
			if strings.TrimSpace(refTitle) == "" {
				refTitle = "Command reference"
			}

			// Hash refs against the git toplevel — the SAME base the drift checker
			// (`check docs`) uses — so generation and verification always agree
			// regardless of which subdirectory selfdoc is invoked from.
			repo, err := git.Open(cmd.Context(), ".")
			if err != nil {
				return Fail(CodeError, fmt.Errorf("selfdoc must run inside the CLI git repo: %w", err))
			}

			refBlocks, err := buildCommandReferenceBlocks(root, repo.Root)
			if err != nil {
				return Fail(CodeError, err)
			}
			overviewBlocks := buildOverviewBlocks()

			pages := []api.PageUpsertRequest{
				{SpaceSlug: sp, Slug: "command-reference", Title: refTitle, Blocks: refBlocks},
				{SpaceSlug: sp, Slug: "overview", Title: "Overview", Blocks: overviewBlocks},
			}

			out := cmd.OutOrStdout()

			if output == outputStdout {
				for _, p := range pages {
					printSelfdocPageText(out, p)
				}
				return nil
			}

			if dryRun {
				return printSelfdocDryRun(out, sp, site, pages)
			}

			if err := e.requireAuth(); err != nil {
				return err
			}

			if _, err := e.client.EnsureSpace(cmd.Context(), site, api.SpaceUpsertRequest{
				Slug:        sp,
				Name:        "Gravity CLI",
				Description: selfdocSpaceDescription,
			}); err != nil {
				return selfdocAPIError(err, "ensure space")
			}

			for _, p := range pages {
				resp, err := e.client.UpsertPage(cmd.Context(), site, p)
				if err != nil {
					return selfdocAPIError(err, fmt.Sprintf("upsert page %q", p.Slug))
				}
				fmt.Fprintf(out, "Proposed page: %s\n", resp.PageSlug)
				fmt.Fprintf(out, "Status:   %s\n", resp.Status)
				fmt.Fprintf(out, "Proposal: %s\n", resp.ProposalID)
				fmt.Fprintf(out, "Review:   %s\n\n", resp.ReviewURL)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&space, "space", "", "target space slug (default: cli)")
	cmd.Flags().StringVar(&output, "output", outputProposal, "proposal|stdout")
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "print the JSON that would be posted without calling the API")
	cmd.Flags().StringVar(&title, "title", "", "override the command-reference page title")
	return cmd
}

// selfdocAPIError wraps an error, surfacing a helpful auth hint for *api.APIError.
func selfdocAPIError(err error, what string) error {
	var ae *api.APIError
	if errors.As(err, &ae) && ae.IsAuth() {
		return Failf(CodeError, "%s: %s (check --token / GRAVITY_TOKEN and that the key is authorized for this site)", what, ae.Message)
	}
	return Fail(CodeError, fmt.Errorf("%s: %w", what, err))
}

// cliSourceBinding builds a drift-verifiable binding for a machine block.
// ref is a repo-relative FILE path under repoRoot; the hash is sha256 of that
// file's bytes at generation time. If the file cannot be hashed (e.g. the
// binary is not running from the CLI repo root), the binding falls back to
// rootSourceRef so the ref always resolves to a real repo file.
func cliSourceBinding(repoRoot, ref string) (*api.SourceBinding, error) {
	hash, err := hashRepoFile(repoRoot, ref)
	if err != nil {
		// Fall back to the root command file, which is always present.
		if ref != rootSourceRef {
			if h2, err2 := hashRepoFile(repoRoot, rootSourceRef); err2 == nil {
				return &api.SourceBinding{
					Kind:      "cli",
					Ref:       rootSourceRef,
					Hash:      "sha256:" + h2,
					Generator: "gravity selfdoc v" + version,
				}, nil
			}
		}
		return nil, fmt.Errorf("hash source %q: %w", ref, err)
	}
	return &api.SourceBinding{
		Kind:      "cli",
		Ref:       ref,
		Hash:      "sha256:" + hash,
		Generator: "gravity selfdoc v" + version,
	}, nil
}

// hashRepoFile computes the lowercase hex sha256 of repoRoot/ref, rejecting
// directories and ".." escapes so the binding mirrors the drift checker's rules.
func hashRepoFile(repoRoot, ref string) (string, error) {
	if filepath.IsAbs(ref) {
		return "", fmt.Errorf("ref is absolute")
	}
	clean := filepath.Clean(ref)
	if clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("ref escapes repo root")
	}
	abs := filepath.Join(repoRoot, clean)
	info, err := os.Stat(abs)
	if err != nil {
		return "", err
	}
	if info.IsDir() {
		return "", fmt.Errorf("ref is a directory")
	}
	f, err := os.Open(abs)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// walkCommands returns the visible (non-hidden, non-help) command leaves and
// groups of the tree, depth-first, each with its space-joined name path.
type cmdNode struct {
	path string // e.g. "check api"
	cmd  *cobra.Command
}

func walkCommands(root *cobra.Command) []cmdNode {
	var out []cmdNode
	var rec func(c *cobra.Command, prefix string)
	rec = func(c *cobra.Command, prefix string) {
		children := c.Commands()
		// Stable order for deterministic output.
		sorted := make([]*cobra.Command, 0, len(children))
		sorted = append(sorted, children...)
		sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name() < sorted[j].Name() })
		for _, child := range sorted {
			if child.Hidden || child.Name() == "help" || !child.IsAvailableCommand() {
				continue
			}
			path := child.Name()
			if prefix != "" {
				path = prefix + " " + child.Name()
			}
			out = append(out, cmdNode{path: path, cmd: child})
			rec(child, path)
		}
	}
	rec(root, "")
	return out
}

// sourceRefFor returns the most specific known repo file for a command path.
func sourceRefFor(path string) string {
	if ref, ok := commandSourceRefs[path]; ok {
		return ref
	}
	return rootSourceRef
}

func buildCommandReferenceBlocks(root *cobra.Command, repoRoot string) ([]api.BlockInput, error) {
	nodes := walkCommands(root)

	var blocks []api.BlockInput
	pos := 0
	add := func(typ string, content any, ref string) error {
		sb, err := cliSourceBinding(repoRoot, ref)
		if err != nil {
			return err
		}
		blocks = append(blocks, api.BlockInput{
			Key:           fmt.Sprintf("cmdref-%d", pos),
			Type:          typ,
			Ownership:     "machine",
			Content:       content,
			SourceBinding: sb,
			Position:      pos,
		})
		pos++
		return nil
	}

	// Title heading + intro prose, bound to the root command file.
	if err := add("heading", map[string]any{
		"text":  fmt.Sprintf("%s — command reference", root.Name()),
		"level": 1,
	}, rootSourceRef); err != nil {
		return nil, err
	}
	if err := add("prose", map[string]any{
		"text": fmt.Sprintf(
			"%s\n\nThis reference is generated from the CLI's own command tree by `gravity selfdoc` (version %s). Every block is bound to its source file and re-verified by the drift checker, so it cannot silently fall out of sync with the binary.",
			strings.TrimSpace(firstLine(root.Long, root.Short)), version,
		),
	}, rootSourceRef); err != nil {
		return nil, err
	}

	// Commands table: name path, short summary.
	cmdRows := [][]string{{"Command", "Summary"}}
	for _, n := range nodes {
		cmdRows = append(cmdRows, []string{root.Name() + " " + n.path, oneLine(n.cmd.Short)})
	}
	if err := add("heading", map[string]any{"text": "Commands", "level": 2}, rootSourceRef); err != nil {
		return nil, err
	}
	if err := add("table", map[string]any{"rows": cmdRows, "header": true}, rootSourceRef); err != nil {
		return nil, err
	}

	// Per-command sections: heading + usage code + flags table, each bound to the
	// command's own source file (falling back to root.go).
	for _, n := range nodes {
		ref := sourceRefFor(n.path)
		full := root.Name() + " " + n.path

		if err := add("heading", map[string]any{"text": full, "level": 3}, ref); err != nil {
			return nil, err
		}
		desc := oneLine(n.cmd.Short)
		if l := strings.TrimSpace(n.cmd.Long); l != "" {
			desc = strings.TrimSpace(l)
		}
		if desc != "" {
			if err := add("prose", map[string]any{"text": desc}, ref); err != nil {
				return nil, err
			}
		}
		if err := add("code", map[string]any{
			"text":     usageLine(full, n.cmd),
			"language": "bash",
		}, ref); err != nil {
			return nil, err
		}
		if rows := flagRows(n.cmd); len(rows) > 1 {
			if err := add("table", map[string]any{"rows": rows, "header": true}, ref); err != nil {
				return nil, err
			}
		}
	}

	// Persistent (global) flags, bound to root.go where they are declared.
	if rows := persistentFlagRows(root); len(rows) > 1 {
		if err := add("heading", map[string]any{"text": "Global flags", "level": 2}, rootSourceRef); err != nil {
			return nil, err
		}
		if err := add("prose", map[string]any{
			"text": "These persistent flags are available on every command.",
		}, rootSourceRef); err != nil {
			return nil, err
		}
		if err := add("table", map[string]any{"rows": rows, "header": true}, rootSourceRef); err != nil {
			return nil, err
		}
	}

	// Exit-code contract, bound to exit.go.
	if err := add("heading", map[string]any{"text": "Exit codes", "level": 2}, "internal/cli/exit.go"); err != nil {
		return nil, err
	}
	if err := add("table", map[string]any{
		"rows": [][]string{
			{"Code", "Meaning"},
			{fmt.Sprintf("%d", CodeOK), "Success / no findings"},
			{fmt.Sprintf("%d", CodeFindings), "Findings produced (drift, gaps, stale bindings)"},
			{fmt.Sprintf("%d", CodeError), "Operational error (auth, network, bad input)"},
		},
		"header": true,
	}, "internal/cli/exit.go"); err != nil {
		return nil, err
	}

	return blocks, nil
}

func buildOverviewBlocks() []api.BlockInput {
	intro := "# Gravity CLI\n\n" +
		"The Gravity CLI is the CI/pipeline companion for the Gravity docs platform. " +
		"It generates release notes from git history, checks API-doc drift and docs completeness against your code, " +
		"and keeps this very space — its own documentation — current via `gravity selfdoc`.\n\n" +
		"The companion **Command reference** page is generated automatically from the CLI's command tree and is drift-locked to the source; " +
		"this overview is yours to edit — add install notes, CI snippets, or team conventions here."
	return []api.BlockInput{
		{
			Key:       "overview-intro",
			Type:      "prose",
			Ownership: "hybrid",
			Content:   map[string]any{"text": intro},
			Position:  0,
		},
	}
}

// --- text/JSON rendering helpers ---

func printSelfdocDryRun(w io.Writer, space, site string, pages []api.PageUpsertRequest) error {
	fmt.Fprintf(w, "--- dry run: gravity selfdoc (site %q, space %q) ---\n", site, space)
	fmt.Fprintln(w, "Would EnsureSpace:")
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	if err := enc.Encode(api.SpaceUpsertRequest{
		Slug: space, Name: "Gravity CLI", Description: selfdocSpaceDescription,
	}); err != nil {
		return Fail(CodeError, err)
	}
	for _, p := range pages {
		fmt.Fprintf(w, "Would UpsertPage %q:\n", p.Slug)
		if err := enc.Encode(p); err != nil {
			return Fail(CodeError, err)
		}
	}
	return nil
}

func printSelfdocPageText(w io.Writer, p api.PageUpsertRequest) {
	fmt.Fprintf(w, "# %s  (slug: %s, space: %s)\n\n", p.Title, p.Slug, p.SpaceSlug)
	for _, b := range p.Blocks {
		bind := ""
		if b.SourceBinding != nil {
			bind = fmt.Sprintf("  [%s %s]", b.SourceBinding.Kind, b.SourceBinding.Ref)
		}
		fmt.Fprintf(w, "[%d] %s (%s)%s\n", b.Position, b.Type, b.Ownership, bind)
		fmt.Fprintf(w, "    %s\n", oneLine(blockSummary(b)))
	}
	fmt.Fprintln(w)
}

// blockSummary renders a short human-readable preview of a block's content.
func blockSummary(b api.BlockInput) string {
	m, ok := b.Content.(map[string]any)
	if !ok {
		return ""
	}
	switch b.Type {
	case "heading", "prose", "code":
		if t, ok := m["text"].(string); ok {
			return t
		}
	case "table":
		if rows, ok := m["rows"].([][]string); ok {
			return fmt.Sprintf("%d row(s)", len(rows))
		}
	}
	return ""
}

// --- cobra introspection helpers ---

// usageLine builds a representative invocation line for a command.
func usageLine(fullPath string, c *cobra.Command) string {
	line := fullPath
	if c.HasAvailableSubCommands() {
		line += " <subcommand>"
	}
	if c.HasAvailableLocalFlags() {
		line += " [flags]"
	}
	return line
}

// flagRows builds a [name, default, description] table for a command's local flags.
func flagRows(c *cobra.Command) [][]string {
	rows := [][]string{{"Flag", "Default", "Description"}}
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		rows = append(rows, []string{"--" + f.Name, f.DefValue, oneLine(f.Usage)})
	})
	return rows
}

// persistentFlagRows builds the same table for the root's persistent flags.
func persistentFlagRows(root *cobra.Command) [][]string {
	rows := [][]string{{"Flag", "Default", "Description"}}
	root.PersistentFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		rows = append(rows, []string{"--" + f.Name, f.DefValue, oneLine(f.Usage)})
	})
	return rows
}

// oneLine collapses whitespace/newlines into a single trimmed line.
func oneLine(s string) string {
	return strings.Join(strings.Fields(s), " ")
}

// firstLine returns long if non-empty, else short.
func firstLine(long, short string) string {
	if strings.TrimSpace(long) != "" {
		return long
	}
	return short
}
